#!/usr/bin/env sh

code --install-extension adamhartford.vscode-base64
code --install-extension AndrsDC.base16-themes
code --install-extension arcticicestudio.nord-visual-studio-code
code --install-extension asvetliakov.vscode-neovim
code --install-extension benjpas.close-all
code --install-extension brettlempereur.theme-base16grayscale
code --install-extension christian-kohler.npm-intellisense
code --install-extension christian-kohler.path-intellisense
code --install-extension dakara.dakara-foldplus
code --install-extension dbankier.vscode-quick-select
code --install-extension donjayamanne.githistory
code --install-extension ecmel.vscode-html-css
code --install-extension EditorConfig.EditorConfig
code --install-extension eriklynd.json-tools
code --install-extension formulahendry.auto-rename-tag
code --install-extension formulahendry.code-runner
code --install-extension fosshaas.fontsize-shortcuts
code --install-extension golang.go
code --install-extension GregorBiswanger.json2ts
code --install-extension Gruntfuggly.todo-tree
code --install-extension gurayyarar.editorenhancements
code --install-extension kleber-swf.ocean-dark-extended
code --install-extension mikestead.dotenv
code --install-extension nick-rudenko.back-n-forth
code --install-extension o4x.base16-tomorrow
code --install-extension octref.vetur
code --install-extension pflannery.vscode-versionlens
code --install-extension quicktype.quicktype
code --install-extension royaction.color-manager
code --install-extension sburg.vscode-javascript-booster
code --install-extension shardulm94.trailing-spaces
code --install-extension sleistner.vscode-fileutils
code --install-extension svipas.control-snippets
code --install-extension tinkertrain.theme-panda
code --install-extension vincaslt.highlight-matching-tag
code --install-extension wayou.vscode-todo-highlight
code --install-extension wmaurer.change-case
code --install-extension yatki.vscode-surround
